version: '3'
services:
  prisma:
    env_file:
      - .env
    depends_on: 
      - db
    image: prismagraphql/prisma:1.13
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: postgres
            active: true
            host: db
            port: 5432
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
  db:
    image: sly613/dev-psql
    ports:
      - 5432:5432
    restart: always 
